name: shift-scheduler
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shift_scheduler_postgres
    restart: always
    environment:
      POSTGRES_DB: shift_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - '127.0.0.1:5434:5432'
    volumes:
      - shift_scheduler_postgres_data:/var/lib/postgresql/data
    networks:
      - shift_scheduler_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: shift_scheduler_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nextlaunchkit.com
      PGADMIN_DEFAULT_PASSWORD: nextlaunchkit123
    ports:
      - '127.0.0.1:5052:80'
    depends_on:
      - postgres
    networks:
      - shift_scheduler_network

volumes:
  shift_scheduler_postgres_data:

networks:
  shift_scheduler_network:
    external: false
